services:
  redpanda:
    image: redpandadata/redpanda:v24.3.1
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      # Internal port 29092 for other containers, 9092 for your host machine
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "9644:9644"

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.8.0
    container_name: redpanda-console
    depends_on:
      - redpanda
    ports:
      - "8085:8080"
    environment:
      KAFKA_BROKERS: redpanda:29092

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ledger_core

  springboot-app:
    build: .
    container_name: fintech-app
    depends_on:
      redpanda:
        condition: service_started
      postgres:
        condition: service_started
    environment:
      # Kafka Connection
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:29092

      # Main DB (Postgres)
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/loan_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"